# Header
menu:
  - {name: Home, path: /, class: icon-home, layout: 1}
  - {name: About, path: /about, class: icon-user, layout: 2}
  - {name: Archives, path: /archives, class: icon-archive, layout: 2}
  - {name: Tags, path: /tags, class: icon-tags, layout: 2}
  - {name: Pictures, path: /picture, class: icon-camera, layout: 2}
  - {name: Works, path: /works, class: icon-trophy, layout: 2}

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: top
widgets:
- category
- recent_posts
- links
- ukagaka

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus: 108158678174364359204
fb_admins:
fb_app_id:

# Google sitemap
google_siteVerification:
  id: 5mRgj8NanEMpGZuNfHNJNmH90RgNlrnJXsFlTaKD6Gs

# Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

## social
facebook_url: https://www.facebook.com/Morris1028
github_url: https://github.com/morris821028
google_plus_url: https://plus.google.com/u/0/108158678174364359204
uhunt_url: http://uhunt.felix-halim.net/id/46705
